definitions.import_backend = local_filesystem
definitions.local.path = /opt/definitions.json

# reload only if file changed
definitions.skip_if_unchanged = true

# reduce logging of annoying authentication events
log.user.level = warning
