name: rabbitmq-scheduler-poc
services:
  rabbitmq:
    image: rabbitmq:4.3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: firqua
      RABBITMQ_DEFAULT_PASS: firqua1234
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq/definitions.json:/opt/definitions.json:ro

  persistence:
    image: postgres:18-alpine
    ports:
      - "55432:5432"
    environment:
      POSTGRES_USER: firqua
      POSTGRES_PASSWORD: firqua1234
      POSTGRES_DB: firqua
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
      start_interval: 1s
